[shop_detail]
country = "it"
sitename = "jdsports_it"
site_address = "https://www.jdsports.it/"
sitemap_address = "https://www.jdsports.it/sitemaps/it-it_desktop_product_0.xml"
[shop_config]
is_gzip = true
timeout = 15
delay = 1
requests = 500
[custom_headers]
user_agent = "Firefox"