[shop_detail]
country = "uk"
sitename = "nordicnest_com"
site_address = "https://www.nordicnest.com/"
sitemap_address = "https://www.nordicnest.com/api/sitemap/en-us/sitemapindex.xml"
[shop_config]
is_gzip = false
timeout = 15
delay = 1
requests = 500
[custom_headers]
user_agent = "Firefox"